// Auto-generated by LibreLane
module uart_tx(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input tx_start,
  input[7:0] tx_data,
  output tx,
  output busy
);
endmodule
